### ISSUE TITLE
747-8 knobs cannot return to previous positions

### ISSUE THREAD

**Issue by FirstOfficerDelta** [LincolnWorks-FlightGear/747-8i#1]
Hello!

Apparently, I cannot turn the knobs for the Hydraulics and APU...

**Comment by ItzLincoln** [comment]
Hello, We have taken note of the issue and are on the case. However it must be noted that the LW team are all unavailable (eg on holiday). We will try to fix this as soon as we can!

**Comment by FirstOfficerDelta** [comment]
Thanks for the clarification! Wishing the best for the B747 development!

**Comment by legoboyvdlp** [comment]
Check if middle mouse button works?

**Comment by FirstOfficerDelta** [comment]
Both clicking with LMB and rolling it with MMB does not work.

Edit: Fixed issue in personal modifications.
